apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyhouse-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyhouse-mongo
  template:
    metadata:
      labels:
        app: tinyhouse-mongo
    spec:
      containers:
        - name: tinyhouse-mongo
          image: mongo:4.2.6-bionic
